baseurl = "http://stav.github.io/"
languageCode = "en-us"
title = "Stav's Awesome Hugo Site"
theme = "hugo-theme-bleak"

[params]
  author = "Steven Almeroth"
  description = "Stav's Awesome Hugo Site"
  githubuser = "stav"
