baseurl = "http://stav.github.io/"
languageCode = "en-us"
title = "My stuff about computers"
description = "O stuff here is."
theme = "hugo-zen"
copyright = "2016 Steven Almeroth"

[params]
  author = "Steven Almeroth"
  description = "Stav's Awesome Hugo Site"
  githubuser = "stav"
  logo = "/images/O.png"
